exports.LOGIN_REQUEST = 'LOGIN_REQUEST'
exports.LOGIN_SUCCESS = 'LOGIN_SUCCESS'
exports.LOGIN_FAIL = 'LOGIN_FAIL'

exports.REGISTER_BOOKING_REQUEST = 'REGISTER_BOOKING_REQUEST'
exports.REGISTER_BOOKING_SUCCESS = 'REGISTER_BOOKING_SUCCESS'
exports.REGISTER_BOOKING_FAIL = 'REGISTER_BOOKING_FAIL'


exports.COMMENT_BOOKING_REQUEST = 'COMMENT_BOOKING_REQUEST'
exports.COMMENT_BOOKING_SUCCESS = 'COMMENT_BOOKING_SUCCESS'
exports.COMMENT_BOOKING_FAIL = 'COMMENT_BOOKING_FAIL'

exports.LOAD_BOOKING_REQUEST = 'LOAD_BOOKING_REQUEST'
exports.LOAD_BOOKING_SUCCESS = 'LOAD_BOOKING_SUCCESS'
exports.LOAD_BOOKING_FAIL = 'LOAD_BOOKING_FAIL'

exports.UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST'
exports.UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
exports.UPDATE_PROFILE_RESET = 'UPDATE_PROFILE_RESET'
exports.UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL'

exports.UPDATE_PASSWORD_REQUEST = 'UPDATE_PASSWORD_REQUEST'
exports.UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS'
exports.UPDATE_PASSWORD_RESET = 'UPDATE_PASSWORD_RESET'
exports.UPDATE_PASSWORD_FAIL = 'UPDATE_PASSWORD_FAIL'

exports.FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST'
exports.FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS'
exports.FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL'

exports.NEW_PASSWORD_REQUEST = 'NEW_PASSWORD_REQUEST'
exports.NEW_PASSWORD_SUCCESS = 'NEW_PASSWORD_SUCCESS'
exports.NEW_PASSWORD_FAIL = 'NEW_PASSWORD_FAIL'

exports.ALL_BOOKINGS_REQUEST = 'ALL_BOOKINGS_REQUEST'
exports.ALL_BOOKINGS_SUCCESS = 'ALL_BOOKINGS_SUCCESS'
exports.ALL_BOOKINGS_FAIL = 'ALL_BOOKINGS_FAIL'

exports.BOOKING_DETAILS_REQUEST = 'BOOKING_DETAILS_REQUEST'
exports.BOOKING_DETAILS_SUCCESS = 'BOOKING_DETAILS_SUCCESS'
exports.BOOKING_DETAILS_FAIL = 'BOOKING_DETAILS_FAIL'

exports.UPDATE_BOOKING_REQUEST = 'UPDATE_BOOKING_REQUEST'
exports.UPDATE_BOOKING_SUCCESS = 'UPDATE_BOOKING_SUCCESS'
exports.UPDATE_BOOKING_RESET = 'UPDATE_BOOKING_RESET'
exports.UPDATE_BOOKING_FAIL = 'UPDATE_BOOKING_FAIL'

exports.DELETE_BOOKING_REQUEST = 'DELETE_BOOKING_REQUEST'
exports.DELETE_BOOKING_SUCCESS = 'DELETE_BOOKING_SUCCESS'
exports.DELETE_BOOKING_RESET = 'DELETE_BOOKING_RESET'
exports.DELETE_BOOKING_FAIL = 'DELETE_BOOKING_FAIL'

exports.LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
exports.LOGOUT_FAIL = 'LOGOUT_FAIL'

exports.CLEAR_ERRORS = 'CLEAR_ERRORS'