exports.LOGIN_REQUEST = 'LOGIN_REQUEST'
exports.LOGIN_SUCCESS = 'LOGIN_SUCCESS'
exports.LOGIN_FAIL = 'LOGIN_FAIL'

exports.REGISTER_EMPLOYEE_REQUEST = 'REGISTER_EMPLOYEE_REQUEST'
exports.REGISTER_EMPLOYEE_SUCCESS = 'REGISTER_EMPLOYEE_SUCCESS'
exports.REGISTER_EMPLOYEE_FAIL = 'REGISTER_EMPLOYEE_FAIL'


exports.COMMENT_EMPLOYEE_REQUEST = 'COMMENT_EMPLOYEE_REQUEST'
exports.COMMENT_EMPLOYEE_SUCCESS = 'COMMENT_EMPLOYEE_SUCCESS'
exports.COMMENT_EMPLOYEE_FAIL = 'COMMENT_EMPLOYEE_FAIL'

exports.LOAD_EMPLOYEE_REQUEST = 'LOAD_EMPLOYEE_REQUEST'
exports.LOAD_EMPLOYEE_SUCCESS = 'LOAD_EMPLOYEE_SUCCESS'
exports.LOAD_EMPLOYEE_FAIL = 'LOAD_EMPLOYEE_FAIL'

exports.UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST'
exports.UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
exports.UPDATE_PROFILE_RESET = 'UPDATE_PROFILE_RESET'
exports.UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL'

exports.UPDATE_PASSWORD_REQUEST = 'UPDATE_PASSWORD_REQUEST'
exports.UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS'
exports.UPDATE_PASSWORD_RESET = 'UPDATE_PASSWORD_RESET'
exports.UPDATE_PASSWORD_FAIL = 'UPDATE_PASSWORD_FAIL'

exports.FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST'
exports.FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS'
exports.FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL'

exports.NEW_PASSWORD_REQUEST = 'NEW_PASSWORD_REQUEST'
exports.NEW_PASSWORD_SUCCESS = 'NEW_PASSWORD_SUCCESS'
exports.NEW_PASSWORD_FAIL = 'NEW_PASSWORD_FAIL'

exports.ALL_EMPLOYEES_REQUEST = 'ALL_EMPLOYEES_REQUEST'
exports.ALL_EMPLOYEES_SUCCESS = 'ALL_EMPLOYEES_SUCCESS'
exports.ALL_EMPLOYEES_FAIL = 'ALL_EMPLOYEES_FAIL'

exports.EMPLOYEE_DETAILS_REQUEST = 'EMPLOYEE_DETAILS_REQUEST'
exports.EMPLOYEE_DETAILS_SUCCESS = 'EMPLOYEE_DETAILS_SUCCESS'
exports.EMPLOYEE_DETAILS_FAIL = 'EMPLOYEE_DETAILS_FAIL'

exports.UPDATE_EMPLOYEE_REQUEST = 'UPDATE_EMPLOYEE_REQUEST'
exports.UPDATE_EMPLOYEE_SUCCESS = 'UPDATE_EMPLOYEE_SUCCESS'
exports.UPDATE_EMPLOYEE_RESET = 'UPDATE_EMPLOYEE_RESET'
exports.UPDATE_EMPLOYEE_FAIL = 'UPDATE_EMPLOYEE_FAIL'

exports.DELETE_EMPLOYEE_REQUEST = 'DELETE_EMPLOYEE_REQUEST'
exports.DELETE_EMPLOYEE_SUCCESS = 'DELETE_EMPLOYEE_SUCCESS'
exports.DELETE_EMPLOYEE_RESET = 'DELETE_EMPLOYEE_RESET'
exports.DELETE_EMPLOYEE_FAIL = 'DELETE_EMPLOYEE_FAIL'

exports.LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
exports.LOGOUT_FAIL = 'LOGOUT_FAIL'

exports.CLEAR_ERRORS = 'CLEAR_ERRORS'