exports.LOGIN_REQUEST = 'LOGIN_REQUEST'
exports.LOGIN_SUCCESS = 'LOGIN_SUCCESS'
exports.LOGIN_FAIL = 'LOGIN_FAIL'

exports.REGISTER_SERVICE_REQUEST = 'REGISTER_SERVICE_REQUEST'
exports.REGISTER_SERVICE_SUCCESS = 'REGISTER_SERVICE_SUCCESS'
exports.REGISTER_SERVICE_FAIL = 'REGISTER_SERVICE_FAIL'

exports.LOAD_SERVICE_REQUEST = 'LOAD_SERVICE_REQUEST'
exports.LOAD_SERVICE_SUCCESS = 'LOAD_SERVICE_SUCCESS'
exports.LOAD_SERVICE_FAIL = 'LOAD_SERVICE_FAIL'

exports.UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST'
exports.UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
exports.UPDATE_PROFILE_RESET = 'UPDATE_PROFILE_RESET'
exports.UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL'

exports.UPDATE_PASSWORD_REQUEST = 'UPDATE_PASSWORD_REQUEST'
exports.UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS'
exports.UPDATE_PASSWORD_RESET = 'UPDATE_PASSWORD_RESET'
exports.UPDATE_PASSWORD_FAIL = 'UPDATE_PASSWORD_FAIL'

exports.FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST'
exports.FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS'
exports.FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL'

exports.NEW_PASSWORD_REQUEST = 'NEW_PASSWORD_REQUEST'
exports.NEW_PASSWORD_SUCCESS = 'NEW_PASSWORD_SUCCESS'
exports.NEW_PASSWORD_FAIL = 'NEW_PASSWORD_FAIL'

exports.ALL_SERVICES_REQUEST = 'ALL_SERVICES_REQUEST'
exports.ALL_SERVICES_SUCCESS = 'ALL_SERVICES_SUCCESS'
exports.ALL_SERVICES_FAIL = 'ALL_SERVICES_FAIL'

exports.SERVICE_DETAILS_REQUEST = 'SERVICE_DETAILS_REQUEST'
exports.SERVICE_DETAILS_SUCCESS = 'SERVICE_DETAILS_SUCCESS'
exports.SERVICE_DETAILS_FAIL = 'SERVICE_DETAILS_FAIL'

exports.UPDATE_SERVICE_REQUEST = 'UPDATE_SERVICE_REQUEST'
exports.UPDATE_SERVICE_SUCCESS = 'UPDATE_SERVICE_SUCCESS'
exports.UPDATE_SERVICE_RESET = 'UPDATE_SERVICE_RESET'
exports.UPDATE_SERVICE_FAIL = 'UPDATE_SERVICE_FAIL'

exports.DELETE_SERVICE_REQUEST = 'DELETE_SERVICE_REQUEST'
exports.DELETE_SERVICE_SUCCESS = 'DELETE_SERVICE_SUCCESS'
exports.DELETE_SERVICE_RESET = 'DELETE_SERVICE_RESET'
exports.DELETE_SERVICE_FAIL = 'DELETE_SERVICE_FAIL'

exports.LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
exports.LOGOUT_FAIL = 'LOGOUT_FAIL'

exports.CLEAR_ERRORS = 'CLEAR_ERRORS'